gems: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num/"
encoding: "utf-8"
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
tagline: Site Tagline
blog :
  title: 杨桃儿的博客  # 网页标题
  name: Ytaoer Blog # 博客名称
  description: 专注所以专业 # 博客描述
  url: http://ytaoer.com # 博客地址
  duoshuo: liangyangtao  # 多说ID
  tongji: 47b228aed7a3fbabcebe22b7a5a06345 # 百度统计
  qiniu: http://obdna1jlc.bkt.clouddn.com
  miitbeian: 京ICP备16045559号  # 备案号
  
  
author :
  name : 杨桃儿
  email : kf@ytaoer.com
  github : https://github.com/liangyangtao
  twitter : 
  feedburner : 
  weibo: http://weibo.com/2478993465 # 微博地址
  qq: 674613438

production_url : http://www.ytaoer.com


JB :
  version : 0.3.0

  
  BASE_PATH : false

 
  ASSET_PATH : /assets/themes/medigo

  
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : custom
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
    duoshuo :
      short_name : liangyangtao

  analytics :
    provider : google
    gauges :
        site_id : 'SITE ID'
    google : 
        tracking_id : 'UA-123-12'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  sharing :
    provider : false

  pages_list :
    provider : "custom"

  tags_list :
      provider : "custom"
  posts_collate:
    provider: "custom"
    

